//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserve
    {
        public int resarve_id { get; set; }
        public string user_name { get; set; }
        public string name { get; set; }
        public Nullable<int> travel_id { get; set; }
    
        public virtual travels_tb travels_tb { get; set; }
    }
}
