//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class travels_tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public travels_tb()
        {
            this.reserves = new HashSet<reserve>();
        }
    
        public int travel_id { get; set; }
        public string travel_name { get; set; }
        public string travel_from { get; set; }
        public string travel_to { get; set; }
        public System.DateTime travel_time_date { get; set; }
        public decimal travel_price { get; set; }
        public int bus_id { get; set; }
        public int line_id { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual line line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserve> reserves { get; set; }
    }
}
